before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    id: "nodepanels-daemon"
    binary: "nodepanels-daemon-{{ .Os }}-{{ .Arch }}"
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64